### ISSUE TITLE
AssertionError: `HyperlinkedIdentityField` requires the request in the serializer context, again

### ISSUE THREAD

**Issue by jrwiegand** [kevinastone/django-api-rest-and-angular#15]
I am having the same problem as [the closed issue] (https://github.com/kevinastone/django-api-rest-and-angular/issues/12) and I have created the context. Just for a little extra information I am using Python3.4.

![Proof](https://cloud.githubusercontent.com/assets/1606617/6476312/3c357660-c1e2-11e4-91f8-7ac0d2115691.png)

**Comment by cjav** [comment]
Ran into the same issue. It seems the blog post needs to be updated for the `post` serializing example.

From:

    PostSerializer(post).data

To:

    PostSerializer(post, context=context).data

**Comment by jrwiegand** [comment]
Thank you. This worked great.

**Comment by kevinastone** [comment]
Updated, thanks.
