### ISSUE TITLE
Initial migration failing

### ISSUE THREAD

**Issue by nmgeek** [kevinastone/django-api-rest-and-angular#19]
I get this error when the makefile runs the initial migration:
```
django.core.exceptions.FieldDoesNotExist: User_groups has no field named None
```
Maybe this cropped up in the latest version of Django?

I was able to work around this with:
```
  rm example/api/migrations/0001_initial.py*
  rm example/api/migrations/0002_auto_20150525_1522.py*
  ./manage.py makemigrations
```

**Comment by kevinastone** [comment]
I can't reproduce this.  Please re-open if you're still seeing it.
