### ISSUE TITLE
Update installation instruction for libjpeg8-dev

### ISSUE THREAD

**Issue by pmahata** [kevinastone/django-api-rest-and-angular#23]
I got a jpeg ValueError during installation with ```pip install -r requirements.txt```

I found out that needed to install libjpeg8-dev with 

sudo apt-get install libjpeg8-dev

It will be useful to update the installation instruction with this info.

**Comment by kevinastone** [comment]
There's a Vagrantfile and Dockerfile to help you setup your environment.
