### ISSUE TITLE
Clean install none of the examples working

### ISSUE THREAD

**Issue by njbuch** [kevinastone/django-api-rest-and-angular#25]
Hi, I love the blog-post and was eager to play with the code. Sadly, none of it is working. Followed the install instructions to detail and everything running smoothly.

The error are for all (except static) examples:
```
AssertionError: 'PostList' should either include a `queryset` attribute, or over
ride the `get_queryset()` method.
[27/Mar/2016 21:48:15] "GET /api/posts HTTP/1.1" 500 91167
```

My noob-brain cannot help here, sorry...

**Comment by kevinastone** [comment]
I haven't had a chance to update this to match some changes in DRF 😕

**Comment by njbuch** [comment]
Thanks for quick info on this. Tried downgrading the DRF framework to different earlier versions, which did not succeed either - of other people are stuck in this place.

Maybe you would want to add a label with a working version?

**Comment by kevinastone** [comment]
Just pushed a new update that fixes these issues.
