### ISSUE TITLE
errorin setup all environment

### ISSUE THREAD

**Issue by kartikdanidhariya** [kevinastone/django-api-rest-and-angular#29]
hi i tried with your example 
but when i give command likn

npm install
bower install 

so ti show that 
"/usr/bin/env: node: No such file or directory"
 how can i solve this

and when i try to open 
http://localhost:8000/resource
so it shows 

{{ post.title }} {{ post.author.username }}

{{ post.body }}

django template tag as output

**Comment by kevinastone** [comment]
You need to install nodejs

**Comment by kartikdanidhariya** [comment]
nodejs is installed in check from 
nodejs -v
so it return 
v0.10.25

**Comment by kevinastone** [comment]
Ah, you're on debian presumably?  It installs under the wrong name:

http://unix.stackexchange.com/questions/65235/universal-node-js-shebang
