### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by sky1048576** [kevinastone/django-api-rest-and-angular#33]
i can't run this project on my local system 
i get this error:
DoesNotExist at /admin/login/

User matching query does not exist.

Request Method: 	POST
Request URL: 	http://127.0.0.1:8080/admin/login/?next=/admin/
Django Version: 	1.10.4
Exception Type: 	DoesNotExist
Exception Value: 	

User matching query does not exist.

Exception Location: 	C:\Python35\lib\site-packages\django\db\models\query.py in get, line 385
Python Executable: 	C:\Python35\python.exe
Python Version: 	3.5.2
Python Path: 	

['G:\\py36_dj110\\django-api-rest-and-angular-master',
 'C:\\Python35\\python35.zip',
 'C:\\Python35\\DLLs',
 'C:\\Python35\\lib',
 'C:\\Python35',
 'C:\\Python35\\lib\\site-packages']

Server time: 	Tue, 28 Mar 2017 00:37:23 -0700

**Comment by kevinastone** [comment]
Can't help troubleshoot.  There's a docker container to simplify setup if you want to try that.
