### ISSUE TITLE
ImportError: No module named 'example'

### ISSUE THREAD

**Issue by ohmeow** [kevinastone/django-api-rest-and-angular#5]
When running: " make create_database; make make_fixtures"

I get an ImportError:

DJANGO_SETTINGS_MODULE='example.settings' ./scripts/create_users.py
Traceback (most recent call last):
  File "./scripts/create_users.py", line 3, in <module>
    from example.api.models import User
ImportError: No module named 'example'

Using Python 3.3.5 but not sure how to structure the make file so it correctly sees the "example" module.

**Comment by RubenBaez** [comment]
Hi, when i try add a post from angular(http://127.0.0.1/editor) i get a error on linux console(django server):
"POST /api/posts HTTP/1.1" 403 58, can you help me? And on angular alert is displayed in red that says 'detail', thanks
